def configureAxes(ax1, ax2, ax3, ax4, ax5, ax6, time):
    # Fjern for-løkken?
    for ax in [ax1, ax3, ax4, ax6]:
        ax.set_xlim(0, 3000)

    ax2.set_xlim([-1, 1])
    ax2.set_ylim([-1, 1])
    ax2.set_zlim([-1, 1])
    ax1.set_ylim(0, 30)
    ax3.set_ylim(0, 10)
    ax4.set_xlim([-20, 20])
    ax4.set_ylim([-20, 20])
    ax4.set_zlim([-20, 20])
    ax5.set_xscale('log')
    ax5.set_xlim(20, 2000)
    ax5.set_ylim(0, 10000)
    ax6.set_ylim(0, 30)

    ax2.set_xlabel("x-aksen")
    ax2.set_ylabel("y-aksen")
    ax2.set_zlabel("z-aksen")
    ax1.set_title("Akselerasjon", fontweight=500, fontsize=20)
    ax1.set_ylabel("Akselerasjon (m/s²)")
    ax3.set_title("Fart", fontweight=500, fontsize=20)
    ax3.set_ylabel("Fart (m/s)")
    ax1.set_xlabel("Tid (ms)")
    ax3.set_xlabel("Tid (ms)")
    ax2.set_title("Retning", fontweight=500, fontsize=20)
    ax4.set_title("Posisjon", fontweight=500, fontsize=20)
    ax4.set_xlabel("x-aksen")
    ax4.set_ylabel("y-aksen")
    ax4.set_zlabel("z-aksen")
    ax5.set_title("Frekvensspekter", fontweight=500, fontsize=20)
    ax5.set_xlabel("Frekvens (Hz)")
    ax5.set_ylabel("Amplitude")

    ax6.set_xlabel("Tid (ms)")
    ax6.set_ylabel("Newton")
    ax6.set_title("Kollisjonsstyrke")
